env:
  browser: true
  es2022: true

extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  project: backend/tsconfig.json
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 'off'
  prettier/prettier: warn
  quotes:
    - error

plugins:
  - '@typescript-eslint'
  - prettier
